'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { listarReportes, Reporte } from '@/lib/api';
import { PetCard } from '@/components/pets/PetCard';
import { VisualMatchModal } from '@/components/pets/VisualMatchModal';
import { Icono } from '@/components/ui/Icono';

type Filtro = 'todos' | 'perdido' | 'encontrado' | 'alerta_cebo' | 'adopcion';

export default function HomePage() {
  const [reportes, setReportes] = useState<Reporte[]>([]); const [cargando, setCargando] = useState(true); const [filtro, setFiltro] = useState<Filtro>('todos'); const [cotejo, setCotejo] = useState<Reporte | null>(null);
  useEffect(() => { listarReportes().then(setReportes).catch(console.error).finally(() => setCargando(false)); }, []);
  const alertas = reportes.filter((r) => r.report_type === 'alerta_cebo' && !r.is_resolved);
  const avisos = useMemo(() => reportes.filter((r) => filtro === 'todos' || (filtro === 'encontrado' ? ['encontrado', 'en_transito'].includes(r.report_type || '') : r.report_type === filtro)), [reportes, filtro]);
  const filtros: { id: Filtro; label: string }[] = [{ id: 'todos', label: 'Todos' }, { id: 'perdido', label: 'Se busca' }, { id: 'encontrado', label: 'En resguardo' }, { id: 'adopcion', label: 'Hogar y tránsito' }, { id: 'alerta_cebo', label: 'Alertas' }];
  const principal = reportes.find((r) => r.report_type === 'perdido' && !r.is_resolved) || reportes[0];

  return <main className="relative pb-24"><section className="border-b border-borde-fuerte bg-lino-alto"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-9 sm:px-6 lg:grid-cols-[1.2fr_.8fr] lg:px-8 lg:py-14"><div><h1 className="max-w-3xl text-4xl font-extrabold leading-[.94] tracking-[-.04em] sm:text-6xl">Cuando alguien mira, el rastro sigue.</h1><p className="mt-6 max-w-xl text-base leading-relaxed text-corteza-suave sm:text-lg">Publicá una foto, marcá el último lugar visto y conectate con quienes pueden ayudar a encontrarla.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/reportes/nuevo" className="boton-principal inline-flex min-h-12 items-center gap-2 px-5"><Icono nombre="camara" className="size-5" />Crear un aviso</Link><Link href="/mapa" className="inline-flex min-h-12 items-center gap-2 rounded-md border border-corteza px-5 font-bold hover:bg-lino"><Icono nombre="plano" className="size-5" />Ver el mapa</Link></div></div><aside className="border border-borde-fuerte bg-lino p-5 sm:p-6"><p className="rotulo">Cómo ayuda la red</p><div className="mt-5 space-y-4"><p className="text-lg font-bold">Foto, zona y contacto.</p><p className="text-sm leading-relaxed text-corteza-suave">La información importante queda visible para que cada vecino pueda reconocer, ubicar y avisar rápido.</p><div className="border-t border-borde-suave pt-4 text-sm"><Link href="/remum" className="font-bold text-salvia hover:underline">Identificar a mi mascota con REMUM →</Link></div></div></aside></div></section>
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">{alertas.length > 0 && <section className="mb-8 border border-coral bg-coral-50 p-5 sm:flex sm:items-start sm:justify-between"><div className="flex gap-3"><Icono nombre="atencion" className="mt-0.5 size-6 shrink-0 text-coral" /><div><p className="rotulo !text-coral">Alerta sanitaria</p><h2 className="mt-1 text-xl font-extrabold tracking-[-.02em]">Cebo sospechoso informado</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-corteza-suave">{alertas[0].description || 'Revisá la zona antes de pasear y consultá el protocolo de urgencia si sospechás una intoxicación.'}</p></div></div><Link href="/sos" className="mt-4 inline-flex rounded-md border border-coral px-4 py-2 text-sm font-bold text-coral hover:bg-coral hover:text-white sm:mt-0">Ver protocolo</Link></section>}
      {principal && <section className="mb-10 grid overflow-hidden rounded-xl border border-borde-fuerte bg-lino-alto md:grid-cols-[.85fr_1.15fr]"><img src={principal.image_path ? `${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'}${principal.image_path}` : '/favicon.ico'} alt={principal.pet_name || 'Aviso activo'} className="aspect-[16/9] h-full w-full object-cover md:aspect-auto" /><div className="p-6 sm:p-8"><p className="rotulo">Búsqueda activa</p><h2 className="mt-2 text-3xl font-extrabold tracking-[-.04em]">{principal.pet_name ? `Se busca a ${principal.pet_name}` : 'Aviso destacado de la red'}</h2><p className="mt-3 max-w-lg text-corteza-suave">{principal.address || 'San Carlos de Bolívar'} · {new Date(principal.created_at).toLocaleDateString('es-AR')}</p><div className="mt-6 flex flex-wrap gap-3"><Link href={`/mapa?lat=${principal.latitude || -36.2333}&lng=${principal.longitude || -61.1167}`} className="boton-principal inline-flex items-center gap-2 px-4 py-3"><Icono nombre="plano" className="size-4" />Ver zona</Link><button onClick={() => setCotejo(principal)} className="rounded-md border border-terracota px-4 py-3 text-sm font-bold text-terracota hover:bg-terracota-50">Ver coincidencias</button></div></div></section>}
      <div className="flex flex-col justify-between gap-4 border-b border-borde-fuerte pb-4 sm:flex-row sm:items-end"><div><h2 className="text-3xl font-extrabold tracking-[-.04em]">Avisos activos</h2><p className="mt-1 text-sm text-corteza-suave">Elegí una situación para encontrar lo que necesitás.</p></div><span className="font-mono text-xs text-corteza-clara">{cargando ? 'CARGANDO' : `${avisos.length} AVISOS`}</span></div><div className="mt-4 flex gap-2 overflow-x-auto pb-1">{filtros.map((item) => <button key={item.id} onClick={() => setFiltro(item.id)} className={`shrink-0 rounded-md border px-4 py-2 text-sm font-bold ${filtro === item.id ? 'border-corteza bg-corteza text-lino-alto' : 'border-borde-fuerte bg-lino-alto hover:bg-lino'}`}>{item.label}</button>)}</div>
      {cargando ? <p className="py-16 text-center text-corteza-suave">Cargando avisos de la red…</p> : avisos.length ? <div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{avisos.map((r) => <PetCard key={r.id} reporte={r} onVerMatches={setCotejo} />)}</div> : <div className="mt-7 border border-dashed border-borde-fuerte p-12 text-center"><Icono nombre="pata" className="mx-auto size-8 text-corteza-clara" /><h3 className="mt-4 text-xl font-bold">No hay avisos en esta vista.</h3><Link href="/reportes/nuevo" className="mt-4 inline-block font-bold text-terracota hover:underline">Crear el primer aviso</Link></div>}</div>{cotejo && <VisualMatchModal reporte={cotejo} onClose={() => setCotejo(null)} />}</main>;
}
