"""Add address column

Revision ID: b4aa5ad4d589
Revises: 22c0e7f28165
Create Date: 2026-08-21 01:58:25.744630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4aa5ad4d589'
down_revision: Union[str, Sequence[str], None] = '22c0e7f28165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'address')
    # ### end Alembic commands ###
