'use client';

import Link from 'next/link';
import { Reporte, urlDeImagen } from '@/lib/api';
import { Icono } from '@/components/ui/Icono';

export function PetCard({ reporte, onVerMatches }: { reporte: Reporte; onVerMatches?: (reporte: Reporte) => void }) {
  const tipo = reporte.report_type || 'perdido';
  const config = tipo === 'alerta_cebo' ? { text: 'Alerta sanitaria', cls: 'border-coral text-coral bg-coral-50' } : tipo === 'encontrado' ? { text: 'En resguardo', cls: 'border-salvia text-salvia bg-salvia-50' } : tipo === 'adopcion' ? { text: 'Busca hogar', cls: 'border-ambar text-ambar bg-ambar-50' } : tipo === 'en_transito' ? { text: 'Tránsito provisorio', cls: 'border-ambar text-ambar bg-ambar-50' } : { text: 'Se busca', cls: 'border-terracota text-terracota bg-terracota-50' };
  const phone = reporte.contact_phone?.replace(/[^\d+]/g, ''); const whatsApp = phone ? `https://wa.me/${phone}?text=${encodeURIComponent(`Hola, vi el aviso de ${reporte.pet_name || 'la mascota'} en Bolívar Animal.`)}` : null;
  const fecha = (() => { try { return new Date(reporte.created_at).toLocaleDateString('es-AR', { day: '2-digit', month: 'short' }); } catch { return 'Reciente'; } })();
  return <article className="ficha-vecinal group overflow-hidden"><div className="relative aspect-[4/3] bg-lino-suave"><img src={urlDeImagen(reporte.image_path) || '/favicon.ico'} alt={reporte.pet_name || 'Animal en aviso comunitario'} className="size-full object-cover transition-transform duration-300 group-hover:scale-[1.03]" loading="lazy" /><span className={`estado-sello absolute left-3 top-3 px-2 py-1 ${config.cls}`}>{config.text}</span>{reporte.is_resolved && <span className="estado-sello absolute right-3 top-3 bg-salvia px-2 py-1 text-white">Resuelto</span>}</div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-xl font-extrabold tracking-[-.03em]">{reporte.pet_name || (tipo === 'alerta_cebo' ? 'Cebo sospechoso' : 'Sin nombre')}</h3><p className="mt-1 text-sm text-corteza-suave">{reporte.pet_breed || reporte.pet_type || 'Mascota sin identificar'}</p></div><span className="font-mono text-[11px] text-corteza-clara">{fecha}</span></div><div className="mt-4 border-y border-borde-suave py-3"><div className="flex items-center gap-2 text-sm font-semibold"><Icono nombre="chincheta" className="size-4 text-terracota" /><span className="truncate">{reporte.address || 'San Carlos de Bolívar'}</span></div>{reporte.color_description && <p className="mt-2 text-xs text-corteza-suave">Pelaje: {reporte.color_description}</p>}</div><div className="mt-4 grid grid-cols-2 gap-2">{whatsApp ? <a href={whatsApp} target="_blank" rel="noopener noreferrer" className="flex items-center justify-center gap-1.5 rounded-md bg-salvia px-3 py-2.5 text-xs font-bold text-white hover:bg-salvia-600"><Icono nombre="telefono" className="size-4" />Contactar</a> : <Link href={`/mapa?lat=${reporte.latitude || -36.2333}&lng=${reporte.longitude || -61.1167}`} className="flex items-center justify-center gap-1.5 rounded-md border border-borde-fuerte px-3 py-2.5 text-xs font-bold hover:bg-lino"><Icono nombre="plano" className="size-4" />Ver zona</Link>}{onVerMatches ? <button onClick={() => onVerMatches(reporte)} className="rounded-md border border-terracota px-3 py-2.5 text-xs font-bold text-terracota hover:bg-terracota-50">Coincidencias</button> : <Link href="/mapa" className="rounded-md border border-terracota px-3 py-2.5 text-center text-xs font-bold text-terracota hover:bg-terracota-50">Ver aviso</Link>}</div></div></article>;
}
